version: "3.7"

services:

  iot_map:
    build: .
#       restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # self-hosted Mongo 
      - MONGODB_URI=mongodb://host.docker.internal:27017/iotmap
      - DEBUG=express:*

#    links:
#      - mongo
#    depends_on: 
#      - mongo
# 
# in container
#   mongo:
#       container_name: mongo
#       image: mongo:latest
#       restart: always
#   ports:
#       - "27017:27017"
#   volumes:
#       - mongodata:/iotmap-mongo/db